/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["bootstrap"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ag-ui": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run the personal agent over the AG-UI protocol
     * @description Accepts an AG-UI RunAgentInput and streams AG-UI events. The threadId
     *     must identify an existing AegisLink conversation. PostgreSQL history is
     *     authoritative; earlier client messages are not used as trusted history.
     */
    post: operations["runAgent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAgents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listConversations"];
    put?: never;
    post: operations["createConversation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations/{conversationId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: components["parameters"]["ConversationId"];
      };
      cookie?: never;
    };
    get: operations["getConversation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conversations/{conversationId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: components["parameters"]["ConversationId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendMessage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{runId}/events": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        runId: components["parameters"]["RunId"];
      };
      cookie?: never;
    };
    get: operations["streamRunEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{runId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        runId: components["parameters"]["RunId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancelRun"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    StatusResponse: {
      status: string;
    };
    ErrorResponse: {
      code: string;
      message: string;
      requestId: string;
    };
    RegisterRequest: {
      displayName: string;
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    User: {
      id: string;
      displayName: string;
    };
    AuthResponse: {
      user: components["schemas"]["User"];
      agent: components["schemas"]["Agent"];
    };
    Agent: {
      id: string;
      name: string;
      description: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Conversation: {
      id: string;
      agentId: string;
      title: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Message: {
      id: string;
      conversationId: string;
      runId?: string;
      /** @enum {string} */
      role: "user" | "assistant";
      content: string;
      /** Format: int64 */
      sequence: number;
      /** Format: date-time */
      createdAt: string;
    };
    Run: {
      id: string;
      conversationId: string;
      /** @enum {string} */
      status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
      failureCode?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      startedAt?: string;
      /** Format: date-time */
      finishedAt?: string;
    };
    RunEvent: {
      runId: string;
      /** Format: int64 */
      sequence: number;
      /** @enum {string} */
      type:
        | "run.started"
        | "tool.started"
        | "tool.completed"
        | "tool.failed"
        | "message.delta"
        | "message.completed"
        | "run.failed"
        | "run.cancelled";
      payload: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      occurredAt: string;
    };
    AgUiRunAgentInput: {
      /** @description Existing AegisLink conversation identifier */
      threadId: string;
      /** @description Client-generated identifier for this AG-UI run */
      runId: string;
      parentRunId?: string;
      /** @description Agent-owned state supplied by the AG-UI client */
      state: unknown;
      messages: components["schemas"]["AgUiMessage"][];
      tools: {
        [key: string]: unknown;
      }[];
      context: {
        [key: string]: unknown;
      }[];
      forwardedProps: {
        [key: string]: unknown;
      };
    };
    AgUiMessage: {
      id: string;
      /** @enum {string} */
      role:
        | "developer"
        | "system"
        | "assistant"
        | "user"
        | "tool"
        | "reasoning";
      content?:
        | string
        | {
            [key: string]: unknown;
          }[];
    } & {
      [key: string]: unknown;
    };
    ConversationDetail: {
      conversation: components["schemas"]["Conversation"];
      messages: components["schemas"]["Message"][];
      activeRun?: components["schemas"]["Run"];
    };
    BootstrapResponse: {
      user: components["schemas"]["User"];
      agent: components["schemas"]["Agent"];
      model: components["schemas"]["ModelInfo"];
    };
    ModelInfo: {
      /** @description Stable identifier for the configured model profile */
      id: string;
      /** @description Runtime provider used to create the model */
      driver: string;
      /** @description Provider-specific model name */
      name: string;
      capabilities: ("streaming" | "tool-calling")[];
    };
  };
  responses: {
    /** @description Request failed */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    ConversationId: string;
    RunId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
    };
  };
  readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dependencies are ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
      503: components["responses"]["Error"];
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account, Human Principal, Personal Agent, and session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      400: components["responses"]["Error"];
      409: components["responses"]["Error"];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authenticated account and new server-side session */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      400: components["responses"]["Error"];
      401: components["responses"]["Error"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked and cookie cleared */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated User and Personal Agent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      401: components["responses"]["Error"];
    };
  };
  bootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authenticated User, Personal Agent, and model metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BootstrapResponse"];
        };
      };
    };
  };
  runAgent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgUiRunAgentInput"];
      };
    };
    responses: {
      /** @description AG-UI Server-Sent Event stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      400: components["responses"]["Error"];
      404: components["responses"]["Error"];
      409: components["responses"]["Error"];
    };
  };
  listAgents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Personal Agents owned by the authenticated Principal */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            agents: components["schemas"]["Agent"][];
          };
        };
      };
    };
  };
  listConversations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversations ordered by latest activity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            conversations: components["schemas"]["Conversation"][];
          };
        };
      };
    };
  };
  createConversation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          title?: string;
        };
      };
    };
    responses: {
      /** @description Conversation created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            conversation: components["schemas"]["Conversation"];
          };
        };
      };
      400: components["responses"]["Error"];
    };
  };
  getConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: components["parameters"]["ConversationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation and ordered messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationDetail"];
        };
      };
      404: components["responses"]["Error"];
    };
  };
  sendMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: components["parameters"]["ConversationId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          content: string;
        };
      };
    };
    responses: {
      /** @description Message persisted and run queued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message: components["schemas"]["Message"];
            run: components["schemas"]["Run"];
          };
        };
      };
      400: components["responses"]["Error"];
      404: components["responses"]["Error"];
      409: components["responses"]["Error"];
    };
  };
  streamRunEvents: {
    parameters: {
      query?: never;
      header?: {
        "Last-Event-ID"?: number;
      };
      path: {
        runId: components["parameters"]["RunId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent stream of RunEvent objects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      404: components["responses"]["Error"];
    };
  };
  cancelRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        runId: components["parameters"]["RunId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
      404: components["responses"]["Error"];
      409: components["responses"]["Error"];
    };
  };
}
